// SPDX-License-Identifier: AGPL-3.0-or-later
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(root, "docs", "ITERATION-009-FIXTURE-AUDIT.md");

function jsonFiles(directory) {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory()
        ? jsonFiles(path)
        : entry.isFile() && entry.name.endsWith(".json")
          ? [path]
          : [];
    })
    .sort();
}

function fixtureType(fixture) {
  if (Array.isArray(fixture.samples)) return "sample request/response";
  if (Array.isArray(fixture.input) && Number.isInteger(fixture.expectedChecksum)) {
    return "checksum";
  }
  if (Array.isArray(fixture.responsePackets)) return "multi-packet response";
  if (Array.isArray(fixture.stalePackets)) return "stale response";
  if (Array.isArray(fixture.expectedFragments)) return "fragmented request";
  if (fixture.parser && Array.isArray(fixture.payload) && fixture.expectedParsed) {
    return "parser";
  }
  if (fixture.parser && Array.isArray(fixture.response) && fixture.expected) {
    return "captured response";
  }
  if (
    fixture.battery != null &&
    Array.isArray(fixture.dpiStages) &&
    fixture.pollingRateHz != null
  ) {
    return "snapshot contract";
  }
  if (fixture.faultContract && Array.isArray(fixture.cases)) return "fault contract";
  if (Number.isInteger(fixture.expectedCommandIdLittleEndian)) return "command id";
  if (Array.isArray(fixture.falseAlarms)) return "checksum regression";
  if (Number.isInteger(fixture.expectedMatches)) return "device matcher";
  return "unrecognized";
}

function requestResponseKind(type) {
  if (type === "sample request/response") return "request + response";
  if (type === "captured response" || type === "parser" || type.includes("response")) {
    return "response";
  }
  if (type.includes("request") || type === "command id" || type === "checksum") {
    return "request";
  }
  if (type.endsWith("contract")) return "structured input";
  return "contract data";
}

const rows = [];
for (const pluginEntry of readdirSync(join(root, "plugins"), { withFileTypes: true })) {
  if (!pluginEntry.isDirectory()) continue;
  const fixtureRoot = join(root, "plugins", pluginEntry.name, "tests", "fixtures");
  if (!existsSync(fixtureRoot)) continue;
  for (const path of jsonFiles(fixtureRoot)) {
    const fixture = JSON.parse(readFileSync(path, "utf8"));
    const type = fixtureType(fixture);
    const hardwareOnly = fixture.hardwareOnly === true;
    rows.push({
      plugin: pluginEntry.name,
      fixture: relative(fixtureRoot, path).replaceAll("\\", "/"),
      type,
      evidence: requestResponseKind(type),
      offline: !hardwareOnly && type !== "unrecognized",
      hardwareOnly,
      final: hardwareOnly
        ? `hardware skip: ${fixture.hardwareReason || "MISSING REASON"}`
        : type === "unrecognized"
          ? "FAIL: add typed executor"
          : "offline typed executor",
    });
  }
}

rows.sort((a, b) => a.plugin.localeCompare(b.plugin) || a.fixture.localeCompare(b.fixture));
const unrecognized = rows.filter((row) => row.type === "unrecognized");
const unexplainedSkips = rows.filter(
  (row) => row.hardwareOnly && row.final.includes("MISSING REASON"),
);
const lines = [
  "# Iteration 009 Fixture Audit",
  "",
  "> Generated by `node scripts/fixture-audit.mjs --write`. CI uses `--check` to prevent drift.",
  "",
  `Summary: ${rows.length} fixtures; ${rows.length - unrecognized.length} recognized; ${unrecognized.length} unrecognized; ${rows.filter((row) => row.hardwareOnly).length} hardware-only; ${unexplainedSkips.length} unexplained skips.`,
  "",
  "| Plugin | Fixture | Schema/type | Request/response | Offline | Real hardware | hardwareOnly | Final handling |",
  "|---|---|---|---|---:|---:|---:|---|",
  ...rows.map(
    (row) =>
      `| ${row.plugin} | ${row.fixture} | ${row.type} | ${row.evidence} | ${row.offline ? "yes" : "no"} | ${row.hardwareOnly ? "yes" : "no"} | ${row.hardwareOnly ? "yes" : "no"} | ${row.final} |`,
  ),
];
const output = `${lines.join("\n")}\n`;

if (process.argv.includes("--write")) {
  writeFileSync(outputPath, output);
  console.log(`wrote ${relative(root, outputPath)} (${rows.length} fixtures)`);
} else if (process.argv.includes("--check")) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
  if (current !== output) {
    console.error(
      `${relative(root, outputPath)} is stale; run node scripts/fixture-audit.mjs --write`,
    );
    process.exitCode = 1;
  }
} else {
  process.stdout.write(output);
}

if (unrecognized.length > 0 || unexplainedSkips.length > 0) {
  console.error(
    `fixture audit failed: ${unrecognized.length} unrecognized, ${unexplainedSkips.length} unexplained skips`,
  );
  process.exitCode = 1;
}
